name: mule4-ci-builder

on:
  workflow_call:
    inputs:
      MAVEN_EXCHANGE_ID:
        type: string
        required: true
    secrets: 
      MAVEN_EXCHANGE_USERNAME:
        type: string
        required: true
      MAVEN_EXCHANGE_PASSWORD:
        type: string
        required: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Java 11
      uses: actions/setup-java@v3
      with:
        java-version: "11"
        distribution: "adopt"
        server-id: ${{ inputs.MAVEN_EXCHANGE_ID }}
        server-username: ${{ secrets.MAVEN_EXCHANGE_USERNAME }}
        server-password: ${{ secrets.MAVEN_EXCHANGE_PASSWORD }}
    
    - name: Build Mule Project
      run: mvn clean package -DskipTests
    
    - name: Run Munit Test Cases
      run: mvn clean test